### ISSUE TITLE
enlarge the size of review sections

### ISSUE THREAD

**Issue by tinynight** [riseshia/neroscape#14]
제대로 된 감상을 적으려는 사람에게 2,000자는 양이 적으므로,
아예 글자수 제한을 없애는 방안을 제안함.

또한, 현재 확인한 결과 2,000자를 넘긴 후 작성하면
붉은 에러 페이지가 뜰 뿐 다른 UI가 없음.
굳이 이 부분이 아니더라도, 글자수 제한을 넣는 부부이라면
해당 제한을 넘긴 시점에서 UI적으로 '이 이상은 작성할 수 없음'을
안내해줄 수 있는 기믹이 있었으면 좋겠음.

단, 봉화처럼 특정 글자수를 넘어가면 장작이 바로 삭제되는 UI/버그 말고.
(단, 브라우저 의존 문제일 수 있음.
체크 시 사용한 브라우저는
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0 SeaMonkey/2.33.1)

**Comment by riseshia** [comment]
Now, limit of text length is updated to 10,000 :+1:
